freeze script

diff --git a/bin/freeze b/bin/freeze
--- a/bin/freeze
+++ b/bin/freeze
@@ -1,5 +1,8 @@
 #!/bin/sh
 
 python freeze.py
+if [ "$?" != "0" ]; then
+    echo 'freeze failed'
+    exit 0
 git add .
 git commit -m 'freeze'
